### ISSUE TITLE
Story: Tracking previously read books. 

### ISSUE THREAD

**Issue by Muskan-R-S** [jennkim0409/CS130_Project#11]
## User Story
As a **user**, I would like to **add books that I have read to my bookshelf** so that **I can view them** later on.

## Detailed Description
Create a way for users to keep track of books that they have already read or are interested in reading.

## Acceptance Criteria
- [x] Given the user signs up for first time, then **they should be able to search and add selected books to their bookshelf.**
- [x] Given the user chooses to **add a book**, then **they should be able to search and add the selected book to their bookshelf.**
- [x] Given the user chooses to **delete a book**, then **they should be able to remove the selected book from the bookshelf**

## Sub-tasks
- [x] #12
- [x] #28 
- [x] #39 
- [x] #43 
- [x] #46
- [x] #41
