### ISSUE TITLE
Epic: Generating book recommendations

### ISSUE THREAD

**Issue by kimcharlene** [jennkim0409/CS130_Project#2]
## Epic
As a user, I want to be able to receive book recommendations based on my chosen preferences.

## User Stories
- [x] User wants to fetch and refresh book recommendations. #4 
- [x] User wants to save books from these recommendations. #5 
- [x] User wants to choose and adjust bubble tags to cater to their current preferences of search. #6
