### ISSUE TITLE
Epic: Making and sharing visual boards

### ISSUE THREAD

**Issue by kimcharlene** [jennkim0409/CS130_Project#3]
## Epic
As a user, I want to make and share visual boards of my books with other users.

## User Stories
- [x] User wants to upload entries for books they choose to reflect on. #7 
- [x] User wants to be able to include their combination of text and images. #8 
- [x] User wants to share and explore other visual boards created by other users. #9
