### ISSUE TITLE
Story: Saving book recommendations

### ISSUE THREAD

**Issue by kimcharlene** [jennkim0409/CS130_Project#5]
## User Story
As a **user**, I would like to **save recommendations** so that **I can come back to my interested books later**.

## Detailed Description
Provide the functionality for the user to save and revisit recommendations they bookmark.

## Acceptance Criteria
- [x] Given the user wants to **save a recommendation**, then they can **bookmark it to be found later.**
- [x] Given the user wants to **revisit their bookmarks**, then they can **find it in a collection of saved book recommendations.**
- [x] Given the user wants to **remove their bookmarks**, then they can **adjust and delete from this collection.**

## Sub-tasks
- [x] #67
