### ISSUE TITLE
Story: uploading visual board entries

### ISSUE THREAD

**Issue by kimcharlene** [jennkim0409/CS130_Project#7]
## User Story
As a **user**, I would like **to create and build visual boards** so that **I can visualize my interpretation of a book**.

## Detailed Description
Create a way for users to visually and creatively interpret their books.

## Acceptance Criteria
- [x] Given **a user wants to create a new entry**, then **they are prompted with a fresh visual board.**
- [x] Given **a user wants to look back into their entries**, then **they can view all existing boards in one place.**
- [x] Given **a user wants to delete an entry**, then **they can remove them from the collection**.

## Sub-tasks
- [x] #34 
- [x] #81
